[package]
name = "delegator-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
workspaces = "0.6.0"
near-abi-client = { path = "../../near-abi-client" }

[dev-dependencies]
tokio = { version = "1.14", features = ["full"] }
