[package]
name = "delegator-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
near-abi-client-macros = { path = "../../near-abi-client-macros" }
workspaces = "0.4.1"

[dev-dependencies]
tokio = { version = "1.14", features = ["full"] }
